### PR TITLE
bulk_replace_one!

### PR DESCRIPTION
**Pull request by ancapdev**
Had a use case for this, and added support for bulk replace operations, if you would please review. Thanks!

### CODE REVIEW

**Comment by felipenoris** [comment]
This is great! Can you add a test?

**Comment by ancapdev** [comment]
Sure, done

**Comment by ancapdev** [comment]
Hey @felipenoris , any chance to merge this soon? I have another addition I'd like to set up a PR for, to add API for setting the cursor batch size. Thanks

**Comment by felipenoris** [comment]
Sure!

**Pull request merged**
